version: 'v0.0'

networks:
  project-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24
          gateway: 10.5.0.1

services:
  db:
    image: redis:7.2
    ports:
      - "6379:6379"
    expose:
      - 6379
    networks:
      project-network:
        ipv4_address: 10.5.0.2
    

  access:
    image: redislabs/redisinsight:1.14.0
    ports:
      - "8001:8001"
    networks:
      - project-network

  manager:
    build: ./manager/
    image: info832/manager:v0
    networks:
      - project-network
    environment:
      - DB_HOST=10.5.0.2
      - DB_PORT=6379
    depends_on:
      - db

  mapper:
    build: ./mapper
    image: info832/mapper:v0
    networks:
      - project-network
    environment:
      - DB_HOST=10.5.0.2
      - DB_PORT=6379
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      - db

  reducer:
    build: ./reducer
    image: info832/reducer:v0
    networks:
      - project-network
    environment:
      - DB_HOST=10.5.0.2
      - DB_PORT=6379
    depends_on:
      - db