apiVersion: apps/v1
kind: Deployment
metadata:
  name:  redis
  namespace: default
  labels:
    app:  redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app:  redis
    spec:
      containers:
      - name:  redis
        
        image:  redis:7.2
        ports:
        - containerPort:  6379
        
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: redis-url


      - name:  redis-insight
        image:  redislabs/redisinsight:1.14.0
        ports:
        - containerPort:  8080
        
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: redis-url

---

apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: redis
  ports:
  - name: redis-port
    protocol: TCP
    port: 6379
    targetPort: 6379
  
  - name: redis-insight
    port: 8080
    targetPort: 8080
    nodePort: 30665